name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Build the project
        run: npm run build

      - name: Prepare SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_KEY }}" | base64 -d > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Deploy to EC2
        env:
          HOST: ${{ secrets.EC2_HOST }}
          USER: ${{ secrets.EC2_USER }}
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa $USER@$HOST << 'EOF'
            # Install necessary tools
            sudo yum update -y
            sudo yum install -y git
            curl -fsSL https://rpm.nodesource.com/setup_16.x | sudo bash -
            sudo yum install -y nodejs
            sudo npm install -g pm2

            # Navigate to your application folder or clone it if not present
            cd /home/ec2-user/clientUI || git clone https://github.com/ECE496-Team-2024900/Clinician-UI /home/ec2-user/clientUI
            cd /home/ec2-user/clientUI

            # Pull latest code and install dependencies
            git pull origin main
            npm install

            # Restart the application
            pm2 restart all || pm2 start npm --name "ClientUI" -- start
          EOF
